braccio_arm:
  #Publish all join states
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50

  #Position Controllers
  base_joint_position_controller:
    type: position_controllers/JointPositionController
    joint: base_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}
  shoulder_joint_position_controller:
    type: position_controllers/JointPositionController
    joint: shoulder_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}
  elbow_joint_position_controller:
    type: position_controllers/JointPositionController
    joint: elbow_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}
  wrist_pitch_joint_position_controller:
    type: position_controllers/JointPositionController
    joint: wrist_pitch_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}
  wrist_roll_joint_position_controller:
    type: position_controllers/JointPositionController
    joint: wrist_roll_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}

                                      
