controller_list:
  - name: fake_arm_controller
    joints:
      - base_joint
      - shoulder_joint
      - elbow_joint
      - wrist_pitch_joint
      - wrist_roll_joint
  - name: fake_gripper_controller
    joints:
      - wrist_pitch_joint
      - wrist_roll_joint
      - gripper_joint